version "4.5"

// Event Handlers for spawning.
#include "zscript/Event-Handlers.zs"

//-------------------------------------------------
// WEAPONS
//-------------------------------------------------

// Black Powder
#include "zscript/weaponry/Musket/Musket.zsc"
#include "zscript/Weaponry/Flintlock Pistol/flintpistol.zsc"

// Defibrillator
#include "zscript/weaponry/Defibrillator/Defib.zsc"

//-------------------------------------------------
// ITEMS
//-------------------------------------------------

// Rations
#include "zscript/Items/UaS_Rations.zs"

// Logistics Bag
#include "zscript/Items/LogiBag.zsc"

// Medical Bag
#include "zscript/Items/MediBag.zsc"

//-------------------------------------------------
// MONSTERS
//-------------------------------------------------

//Trites
#include "zscript/Monsters/Trite.zsc"
#include "zscript/Monsters/TriteBarrel.zsc"